# Generated by Django 5.2.4 on 2025-08-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='coupon_code',
        ),
    ]
