# Generated by Django 5.2.4 on 2025-08-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_offer_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_new',
            field=models.BooleanField(blank=True, default=True, help_text='Show NEW badge', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price (MRP)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Offer price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=5, help_text='Product rating (1-5 stars)', null=True),
        ),
    ]
