# Generated by Django 5.2.4 on 2025-08-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('diapers', 'Diapers & Pampers'), ('dress', 'Baby Dress'), ('soap', 'Baby Soap'), ('stroller', 'Baby Stroller & Prams'), ('toys', 'Toys & Games'), ('others', 'Other Essentials')], default='others', max_length=20),
        ),
    ]
