# Generated by Django 5.2.4 on 2025-08-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_offer_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='category',
        ),
    ]
