# Generated by Django 5.2.4 on 2025-08-07 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_is_new_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='offer',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.product'),
            preserve_default=False,
        ),
    ]
